### ISSUE TITLE
Documentation doesn't build 

### ISSUE THREAD

**Issue by swewers** [MCLF/mclf#14]
Building the documentation doesn't work:

sage -sh
cd docs
make html

produces html files which are essentially empty. The problem seems to be an import statement in monkey.py:
```
WARNING: /home/stefan/Forschung/MCLF/mclf/docs/affinoid_domain.rst:4: (WARNING/2) autodoc: failed to import module u'mclf.berkovich.affinoid_domain'; the following exception was raised:             
Traceback (most recent call last):                                                                 
  File "/home/stefan/comp/sage/sage-8.2/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 657, in import_object                                                                          
    __import__(self.modname)                                                                       
  File "/home/stefan/Forschung/MCLF/mclf/mclf/__init__.py", line 1, in <module>                    
    import monkey                                                                                  
  File "/home/stefan/Forschung/MCLF/mclf/mclf/monkey.py", line 4, in <module>                      
    import sage.rings.valuation.valuation                                                          
  File "/home/stefan/comp/sage/sage-8.2/local/lib/python2.7/site-packages/sage/rings/valuation/valuation.py", line 59, in <module>                                                                    
    from sage.categories.morphism import Morphism                                                  
  File "sage/categories/morphism.pyx", line 1, in init sage.categories.morphism                    
    """                                                                                            
  File "sage/categories/map.pyx", line 1, in init sage.categories.map                              
    r"""                                                                                           
  File "sage/structure/parent.pxd", line 12, in init sage.structure.element                        
    cdef class Parent(sage.structure.category_object.CategoryObject):                              
  File "sage/categories/map.pxd", line 4, in init sage.structure.parent                            
    cdef class Map(Element):                                                                       
AttributeError: 'module' object has no attribute 'Map' 
```

**Comment by swewers** [comment]
The toctree and the main docstring in each module is now visible in the documentation, but the individual classes are not. 
When I build the documentation on my own computer, everything works as it should. Maybe a conflict with different versions of Sphinx? I use 

    .. toctree::

    .. automodule::
       mclf.padic_extensions.fake_padic_completions
       :members:

in the file `fake_padic_completions.rst`, for instance.

**Comment by saraedum** [comment]
It looks good to me. Where are you checking the documentation? http://mclf.readthedocs.io/en/latest/weak_padic_galois_extensions.html for example seems ok to me.

**Comment by swewers** [comment]
No, the docstrings of the classes and methods are not there. In the documentation on my computer, I can see them.

**Comment by swewers** [comment]
Now I can see some of the docstrings of the functions in http://mclf.readthedocs.io/en/latest/smooth_projective_curves.html, but not all.

**Comment by saraedum** [comment]
The main issue is that sphinx refuses to build documentation for classes that inherit from a mock…I hope I managed to fix this now…

**Comment by saraedum** [comment]
It should work now. Please have a look.
